apiVersion: v1
kind: ConfigMap
metadata:
  name: t9-app-config
  namespace: aoc-t9
  labels:
    aoc: t9-target
data:
  LOG_LEVEL: "info"
  HTTP_PORT: "8080"
  GREETING: "hello-from-aoc-t9"
---
apiVersion: v1
kind: Secret
metadata:
  name: t9-app-secret
  namespace: aoc-t9
  labels:
    aoc: t9-target
type: Opaque
stringData:
  USERNAME: "aoc"
  DB_PASSWORD: "AOC-T9-SECRET-MUST-NEVER-BE-PRINTED"
  API_TOKEN: "AOC-T9-TOKEN-MUST-NEVER-BE-PRINTED"
